export const siteName="Dogwise Guide";
export const siteDescription="Clear, practical dog-care guides covering health, safety, nutrition, behavior, training, grooming, breeds, puppies, senior dogs and useful calculators.";
export const categories=[
{slug:"health-safety",name:"Dog Health & Safety",description:"Everyday health questions, warning signs, prevention and household safety topics."},
{slug:"food-nutrition",name:"Food & Nutrition",description:"Feeding basics, nutrition, treats, calories and practical food-safety questions."},
{slug:"behavior-training",name:"Behavior & Training",description:"Reward-based training, communication, puppy behavior and common behavior questions."},
{slug:"care-grooming",name:"Care & Grooming",description:"Bathing, brushing, teeth, nails, ears, exercise and everyday dog care."},
{slug:"dog-breeds",name:"Dog Breeds",description:"Breed characteristics, care considerations and lifestyle-based breed guides."},
{slug:"puppies",name:"Puppies",description:"Puppy feeding, growth, socialization, training, sleep and first-home basics."},
{slug:"senior-dogs",name:"Senior Dogs",description:"Practical senior-dog care, mobility, nutrition and age-related changes."},
{slug:"products-tools",name:"Products & Everyday Life",description:"Dog toys, beds, crates, travel, home setup and everyday ownership."}];
export const tools=[
{slug:"dog-age-calculator",name:"Dog Age Calculator",description:"Estimate your dog's age in human-years terms using a simple life-stage model."},
{slug:"dog-calorie-calculator",name:"Dog Calorie Calculator",description:"Educational daily-calorie estimate using weight, life stage and activity inputs."},
{slug:"dog-feeding-calculator",name:"Dog Feeding Calculator",description:"Convert a daily calorie estimate into an approximate food amount from package calories."},
{slug:"puppy-growth-calculator",name:"Puppy Growth Calculator",description:"Track puppy weight and compare it with a simple growth estimate."},
{slug:"dog-weight-guide",name:"Dog Weight Guide",description:"Educational body-weight and body-condition guide with questions to discuss with a veterinarian."},
{slug:"puppy-feeding-schedule",name:"Puppy Feeding Schedule",description:"A practical age-based feeding schedule framework for puppies."}];
const src={wsava:{name:"WSAVA Global Nutrition Guidelines",url:"https://wsava.org/global-guidelines/global-nutrition-guidelines/"},avsab:{name:"American Veterinary Society of Animal Behavior",url:"https://avsab.org/resources/position-statements/"},aspca:{name:"ASPCA Animal Poison Control",url:"https://www.aspca.org/pet-care/animal-poison-control"}};
export const articles=[
{slug:"dog-age-guide",title:"How Old Is My Dog in Human Years?",category:"care-grooming",description:"A practical explanation of dog age, life stages and why a simple 7-to-1 conversion is not a universal rule.",intro:"People often ask how many human years their dog is. The answer depends on size, breed, life stage and the purpose of the comparison.",sections:[{h:"Why the old 7-to-1 rule is limited",p:"Dogs mature much faster during early life than the simple 7-to-1 rule suggests. A more useful approach is to think in life stages and consider the individual dog's size and health."},{h:"Think in life stages",p:"Puppyhood, adulthood and senior years have different nutrition, exercise and preventive-care needs."}]},
{slug:"dog-calorie-needs",title:"How Many Calories Does a Dog Need?",category:"food-nutrition",description:"Learn what affects a dog's daily energy needs and why calorie estimates should be individualized.",intro:"A dog's calorie requirement depends on factors such as body weight, life stage, activity, reproductive status and health.",sections:[{h:"What changes calorie needs?",p:"Body size, age, activity, growth, pregnancy or nursing and medical conditions can all change energy requirements."},{h:"Body condition matters",p:"Weight alone does not tell the whole story. WSAVA provides body-condition assessment resources and nutrition guidance."}],sources:[src.wsava]},
{slug:"can-dogs-eat-bananas",title:"Can Dogs Eat Bananas?",category:"food-nutrition",description:"A practical food-safety guide to bananas for dogs, including portions, preparation and when to be cautious.",intro:"Banana can be offered to many dogs as an occasional treat, but treats should remain a small part of the overall diet.",sections:[{h:"How to offer banana",p:"Use a small portion, remove the peel and avoid preparations with added sugar or unsafe ingredients."},{h:"Why portion size matters",p:"Bananas contain natural sugars and calories. Large quantities can add more calories than intended and may upset digestion."}]},
{slug:"can-dogs-eat-grapes",title:"Can Dogs Eat Grapes or Raisins?",category:"health-safety",description:"Why grapes and raisins should be treated as a potential poisoning emergency in dogs.",intro:"Grapes and raisins should not be intentionally fed to dogs. Suspected ingestion should be treated as an urgent veterinary matter.",sections:[{h:"What should I do after suspected ingestion?",p:"Contact a veterinarian or appropriate animal poison-control service promptly. Keep the product or packaging available if possible."},{h:"Do not wait for symptoms",p:"A dog can appear normal initially. Waiting for symptoms before seeking advice can delay professional assessment."},{h:"Avoid DIY treatment",p:"Do not induce vomiting or give household substances unless a veterinarian or poison-control professional specifically tells you to do so."}],sources:[src.aspca]},
{slug:"dog-body-language",title:"Dog Body Language: Common Signals Explained",category:"behavior-training",description:"Understand common canine body-language signals without treating one gesture as a guaranteed meaning.",intro:"Dog body language is context-dependent. A tail, ear position, facial expression or posture should be interpreted together with the dog's environment and the rest of its behavior.",sections:[{h:"Look at the whole dog",p:"Loose movement, posture, facial expression, vocalization and the situation all matter."},{h:"Common stress signals",p:"Lip licking, yawning, turning away, lowered posture and attempts to create distance can occur in stressful situations."}],sources:[src.avsab]},
{slug:"reward-based-dog-training",title:"Reward-Based Dog Training: What It Means",category:"behavior-training",description:"An evidence-informed overview of reward-based training and everyday dog skills.",intro:"AVSAB's current public position statement recommends reward-based methods for dog training and behavior modification.",sections:[{h:"What is reward-based training?",p:"Reward-based training reinforces behaviors you want to see with things the dog values, such as food, play or attention."},{h:"Start with small steps",p:"Teach one behavior at a time, reward the behavior you want and gradually increase distractions."}],sources:[src.avsab]},
{slug:"dog-grooming-schedule",title:"Dog Grooming Schedule: A Practical Guide",category:"care-grooming",description:"A flexible dog grooming routine covering brushing, bathing, nails, ears and teeth.",intro:"There is no single grooming schedule that fits every dog. Coat type, activity, skin condition and lifestyle all affect grooming needs.",sections:[{h:"Brushing",p:"Long, dense or curly coats may need frequent brushing to prevent mats. Short coats often need less frequent brushing."},{h:"Bathing",p:"Bathing frequency should match the dog's coat, lifestyle and veterinary advice."}]},
{slug:"dog-house-training",title:"How to House Train a Puppy",category:"puppies",description:"A practical, consistent approach to puppy house training using supervision, routine and reinforcement.",intro:"House training is a process. Puppies need frequent opportunities to eliminate, close supervision and consistent reinforcement.",sections:[{h:"Create a predictable routine",p:"Take the puppy out after waking, eating, drinking, playing and sleeping."},{h:"Reward the behavior you want",p:"When the puppy eliminates in the correct place, reward promptly."},{h:"Handle accidents calmly",p:"Clean accidents thoroughly and avoid punishment. Sudden changes in a previously trained dog should be discussed with a veterinarian."}],sources:[src.avsab]},
{slug:"dog-separation-anxiety-basics",title:"Dog Separation Anxiety: What Owners Should Know",category:"behavior-training",description:"An introduction to separation-related behavior, management and when professional help is appropriate.",intro:"Some dogs become distressed when left alone. Signs and severity vary, and treatment should be tailored to the individual dog.",sections:[{h:"Possible signs",p:"Vocalization, destructive behavior, escape attempts, pacing, house-soiling or intense distress around departures can occur."},{h:"Avoid punishment",p:"Punishing behavior that happens while a dog is distressed can increase fear and does not address the underlying problem."}],sources:[src.avsab]},
{slug:"dog-proof-your-home",title:"How to Dog-Proof Your Home",category:"health-safety",description:"A room-by-room checklist for reducing common household hazards for dogs.",intro:"Dog-proofing is about preventing access to hazards before an accident occurs.",sections:[{h:"Kitchen",p:"Secure foods, trash, medications and cleaning products."},{h:"Bathroom and laundry",p:"Store medicines, detergents, cosmetics and small objects securely."},{h:"Garage and garden",p:"Store chemicals, fertilizers, pesticides and automotive fluids securely."}],sources:[src.aspca]}
];
export const topicLists={
"health-safety":["Dog poisoning","Toxic foods","Toxic plants","Household chemicals","Heat safety","Cold-weather safety","Emergency warning signs","Vomiting","Diarrhea","Dehydration","Allergies","Skin problems","Ear problems","Eye problems","Dental health","Joint health","Obesity","Fleas and ticks","Heartworm basics","Medication safety","Fireworks safety","Holiday hazards"],
"food-nutrition":["Dog nutrition basics","How much should my dog eat?","Dog calories","Treat calories","Reading dog food labels","Dry food","Wet food","Homemade dog food","Raw food","Food allergies","Food intolerance","Puppy nutrition","Adult nutrition","Senior nutrition","Weight management","Can dogs eat bananas?","Can dogs eat strawberries?","Can dogs eat apples?","Can dogs eat blueberries?","Can dogs eat watermelon?","Can dogs eat eggs?","Can dogs eat rice?","Can dogs eat cheese?","Can dogs eat peanut butter?","Can dogs eat chocolate?","Can dogs eat grapes?","Can dogs eat onions?","Can dogs eat garlic?"],
"behavior-training":["Puppy training","House training","Crate training","Leash training","Recall training","Barking","Chewing","Digging","Jumping","Puppy biting","Growling","Resource guarding","Separation-related behavior","Dog body language","Signs of stress","Signs of fear","Why does my dog lick me?","Why does my dog stare at me?","Why does my dog follow me?","Why does my dog paw me?","Why does my dog tilt its head?","Why does my dog howl?","Why does my dog whine?","Why does my dog eat grass?","Reward-based training"],
"care-grooming":["Dog grooming schedule","Bathing","Brushing","Shedding","Nail trimming","Paw care","Ear cleaning","Eye care","Dental care","Teeth brushing","Coat care","Mats and tangles","Exercise","Walking","Mental stimulation","Dog sleep","Dog beds","Dog toys","Microchipping","Routine veterinary care"],
"dog-breeds":["Labrador Retriever","Golden Retriever","German Shepherd","French Bulldog","Poodle","Dachshund","Beagle","Rottweiler","Chihuahua","Shih Tzu","Yorkshire Terrier","Boxer","Doberman","Great Dane","Siberian Husky","Australian Shepherd","Border Collie","Corgi","Pomeranian","Best dogs for apartments","Best family dogs","Best dogs for first-time owners","Low-shedding dogs","Small dog breeds","Large dog breeds","Most affectionate dog breeds","Most intelligent dog breeds","Quiet dog breeds"],
"puppies":["New puppy checklist","First day with a puppy","Puppy sleep","Puppy feeding","Puppy growth","Puppy socialization","Puppy vaccinations","Puppy grooming","Puppy exercise","Puppy-proofing","Puppy biting","Puppy house training","Puppy crate training"],
"senior-dogs":["Senior dog care","Senior dog nutrition","Senior dog exercise","Senior dog mobility","Senior dog grooming","Senior dog sleep","Age-related changes","Weight management for senior dogs"],
"products-tools":["Dog toys","Chew toys","Puzzle toys","Dog beds","Dog crates","Harnesses","Collars","Leashes","Grooming tools","Toothbrushes","Nail clippers","Food bowls","Slow feeders","Travel gear","Dog identification","GPS trackers"]};
